services:
   
  backend:
    build:
      context: backend/api/.
      dockerfile: Dockerfile
    image: ${PROJECT_NAME}-${DEPLOY_ENV}-backend-img
    container_name: ${PROJECT_NAME}-${DEPLOY_ENV}-backend
    env_file:
      - .env
    command: uv run uvicorn app.app:app --host 0.0.0.0 --port 8000
    volumes:
      - ./logs:/logs
      - ./data:/data
    depends_on:
      - redis
    restart: always
    networks:
      - shared_network

  frontend:
    build:
      context: frontend/.
      dockerfile: Dockerfile
    image: ${PROJECT_NAME}-${DEPLOY_ENV}-frontend-img
    container_name: ${PROJECT_NAME}-${DEPLOY_ENV}-frontend
    command: sh -c "npm run preview -- --port=3000 --host"
    networks:
      - shared_network
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
      - VITE_API_BASE_URL=/api
  
  nginx-proxy:
    build:
      context: nginx/.
      dockerfile: Dockerfile
    image: ${PROJECT_NAME}-${DEPLOY_ENV}-nginx-img
    container_name: ${PROJECT_NAME}-${DEPLOY_ENV}-nginx
    depends_on:
      - backend
      - frontend
    environment:
      - ROOT_PATH_BACKEND=${ROOT_PATH_BACKEND}    
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx
      - FRONTEND_SERVICE=frontend
      - BACKEND_SERVICE=backend
    networks:
      - shared_network
    restart: always

  cloudflared:
    build:
      context: cloudflare/.
      dockerfile: Dockerfile
    image: ${PROJECT_NAME}-${DEPLOY_ENV}-cloudflared-img
    container_name: ${PROJECT_NAME}-${DEPLOY_ENV}-cloudflared
    command: tunnel --no-autoupdate run --token $CLOUDFLARED_TOKEN
    networks:
        - shared_network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: ${PROJECT_NAME}-${DEPLOY_ENV}-redis
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - shared_network
    restart: always

  worker-http:
    build:
      context: backend/api/.
      dockerfile: Dockerfile
    image: ${PROJECT_NAME}-${DEPLOY_ENV}-worker-http-img
    container_name: ${PROJECT_NAME}-${DEPLOY_ENV}-worker-http
    env_file:
      - .env
    command: uv run arq app.queue.HttpWorkerSettings
    volumes:
      - ./logs:/logs
      - ./data:/data
    depends_on:
      - redis
    networks:
      - shared_network
    restart: always

  worker-browser:
    build:
      context: backend/api/.
      dockerfile: Dockerfile.browser
    image: ${PROJECT_NAME}-${DEPLOY_ENV}-worker-browser-img
    container_name: ${PROJECT_NAME}-${DEPLOY_ENV}-worker-browser
    env_file:
      - .env
    command: uv run arq app.queue.BrowserWorkerSettings
    volumes:
      - ./logs:/logs
      - ./data:/data
    depends_on:
      - redis
    networks:
      - shared_network
    restart: always

networks:
  shared_network:
    name: ${PROJECT_NAME}-${DEPLOY_ENV}-network
    driver: bridge

volumes:
  redis_data:
    name: ${PROJECT_NAME}-${DEPLOY_ENV}-redis_data-vol
