events {}

http {
  send_timeout 30000s;
  keepalive_timeout 30000s;

  server {
    listen 80;
    return 301 https://$host$request_uri;
  }
  
  server {
    listen 443 ssl;

    ssl_certificate /etc/nginx/certs/internal-server.crt;
    ssl_certificate_key /etc/nginx/certs/internal-server.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers off;

    client_body_timeout 30000s;
    client_header_timeout 30000s;

    # Backend service location
    location /api/ {
      proxy_pass http://${BACKEND_SERVICE}:8000;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto https;

      # WebSocket specific
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";

      rewrite ^/api(/.*)$ $1 break;
      client_max_body_size 100M;
      proxy_read_timeout 30000s;
      proxy_connect_timeout 30000s;
      proxy_send_timeout 30000s;
    }

    # Frontend service location
    location / {
      proxy_pass http://${FRONTEND_SERVICE}:3000;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto https;
    }
  }
}
